JavawebProject/src/com/bookstore/domain/Book.java
package com.bookstore.domain;

import java.sql.Date;

public class Book {

	private Integer book_id;
	private String author;
	private String title;
	private float price;
	private Date publishing_date;
	private int sales_amount;
	private int store_number;
	private String remark;
	public Integer getBook_id() {
		return book_id;
	}
	public void setBook_id(Integer book_id) {
		this.book_id = book_id;
	}
	public String getAuthor() {
		return author;
	}
	public void setAuthor(String author) {
		this.author = author;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public float getPrice() {
		return price;
	}
	public void setPrice(float price) {
		this.price = price;
	}
	public Date getPublishing_date() {
		return publishing_date;
	}
	public void setPublishing_date(Date publishing_date) {
		this.publishing_date = publishing_date;
	}
	public int getSales_amount() {
		return sales_amount;
	}
	public void setSales_amount(int sales_amount) {
		this.sales_amount = sales_amount;
	}
	public int getStore_number() {
		return store_number;
	}
	public void setStore_number(int store_number) {
		this.store_number = store_number;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public Book(Integer book_id, String author, String title, float price, Date publishing_date, int sales_amount,
			int store_number, String remark) {
		super();
		this.book_id = book_id;
		this.author = author;
		this.title = title;
		this.price = price;
		this.publishing_date = publishing_date;
		this.sales_amount = sales_amount;
		this.store_number = store_number;
		this.remark = remark;
	}
	public Book() {
		super();
	}
	@Override
	public String toString() {
		return "Book [book_id=" + book_id + ", author=" + author + ", title=" + title + ", price=" + price
				+ ", publishing_date=" + publishing_date + ", sales_amount=" + sales_amount + ", store_number="
				+ store_number + ", remark=" + remark + "]";
	}
	

}

JavawebProject/src/com/bookstore/domain/ShoppingCart.java
package com.bookstore.domain;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

public class ShoppingCart {
	
	private Map<Integer, ShoppingCartItem> books = new HashMap<>();
	/**
	 * 修改指定购物项的数量
	 */
	public void updateItemQuantity(Integer id,int quantity){
		ShoppingCartItem sci = books.get(id);
		if(sci!=null)
			sci.setQuantity(quantity);
	}
	
	/**
	 * 移除指定的购物项
	 */
	public void removeItem(Integer id){
		books.remove(id);
	}
	
	/**
	 * 清空购物车
	 */
	public void clear(){books.clear();}
	
	/**
	 * 判断购物车是否为空
	 */
	public boolean isEmpty(){return books.isEmpty();}
	
	/**
	 * 获取购物车中的所有的 ShoppingCartItem 组成的集合
	 * @return
	 */
	public Collection<ShoppingCartItem> getItems(){
		return books.values();
	}
	
	/**
	 * 获取购物车中所有的商品的总的钱数
	 */
	public float getTotalMoney(){
		float total = 0;
		for(ShoppingCartItem sci :getItems()){
			total+=sci.getItemMoney();
		}
		return total;
	}
	
	/**
	 * 返回购物车中商品的总数量
	 */
	public int getBookNumber(){
		int total = 0;
		for(ShoppingCartItem sci : books.values()){
			total+=sci.getQuantity();
		}
		return total;
	}
	
	/**
	 * 检验购物车中是否有指定id的商品
	 */
	public boolean hasBook(Integer id){
		return books.containsKey(id);
	}
	
	/**
	 * 向购物车中添加一件商品
	 */
	public void addBook(Book book){
		ShoppingCartItem sci = books.get(book.getBook_id());
		if(sci ==null){
			sci = new ShoppingCartItem(book);
			books.put(book.getBook_id(),sci);
		}else{
			sci.increment();
		}
	}
}

JavawebProject/src/com/bookstore/domain/Trade.java
package com.bookstore.domain;

import java.sql.Date;
import java.util.LinkedHashSet;
import java.util.Set;

public class Trade {

	private Integer trade_id;
	private Date trade_time;
	private Integer user_id;
	private Set<TradeItem> items = new LinkedHashSet<>();
	public Integer getTrade_id() {
		return trade_id;
	}
	public void setTrade_id(Integer trade_id) {
		this.trade_id = trade_id;
	}
	public Date getTrade_time() {
		return trade_time;
	}
	public void setTrade_time(Date trade_time) {
		this.trade_time = trade_time;
	}
	public Integer getUser_id() {
		return user_id;
	}
	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}
	public Set<TradeItem> getItems() {
		return items;
	}
	public void setItems(Set<TradeItem> items) {
		this.items = items;
	}
	public Trade(Integer trade_id, Date trade_time, Integer user_id, Set<TradeItem> items) {
		super();
		this.trade_id = trade_id;
		this.trade_time = trade_time;
		this.user_id = user_id;
		this.items = items;
	}
	public Trade() {
		super();
	}
	@Override
	public String toString() {
		return "Trade [trade_id=" + trade_id + ", trade_time=" + trade_time + ", user_id=" + user_id + ", items="
				+ items + "]";
	}
	
}

JavawebProject/src/com/bookstore/servlet/BookServlet.java
package com.bookstore.servlet;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.domain.Account;
import com.bookstore.domain.Book;
import com.bookstore.domain.ShoppingCart;
import com.bookstore.domain.ShoppingCartItem;
import com.bookstore.domain.User;
import com.bookstore.service.AccountService;
import com.bookstore.service.BookService;
import com.bookstore.service.UserService;
import com.bookstore.web.BookStoreWebUtils;
import com.bookstore.web.CriteriaBook;
import com.bookstore.web.Page;
import com.sun.org.apache.bcel.internal.generic.NEW;

/**
 * Servlet implementation class BookServlet
 */
@WebServlet("/bookServlet")
public class BookServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private BookService bookService = new BookService();
	private UserService userService = new UserService();
	private AccountService accountService = new AccountService();
	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doPost(request, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String methodName = request.getParameter("method");
		try {
			Method method = getClass().getDeclaredMethod(methodName, HttpServletRequest.class,HttpServletResponse.class);
			method.setAccessible(true);
			method.invoke(this,request,response);
		} catch (Exception e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
			throw new RuntimeException(e);
		}
	}
	
	protected void forwardPage(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String page = request.getParameter("page");
		request.getRequestDispatcher("/WEB-INF/pages/"+page+".jsp").forward(request, response);
	}
	
	protected void getBooks(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		int pageNo =1;
		float minPrice = 0;
		float maxPrice = Integer.MAX_VALUE;
	   if(request.getParameter("pageNo")!=null){
		   pageNo = Integer.parseInt(request.getParameter("pageNo"));
	   }
	   if(request.getParameter("minPrice")!=null){
		   minPrice =Float.parseFloat(request.getParameter("minPrice"));
	   }
	   if(request.getParameter("maxPrice")!=null){
		   maxPrice = Float.parseFloat(request.getParameter("maxPrice"));
	   }
		CriteriaBook criteriaBook = new CriteriaBook(minPrice, maxPrice, pageNo);
		Page<Book> page = bookService.getPage(criteriaBook);
		request.setAttribute("bookpage", page);
		request.setAttribute("cb", criteriaBook);
		request.getRequestDispatcher("/WEB-INF/pages/books.jsp").forward(request, response);
	}
	
	protected void getBook(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String idStr = request.getParameter("id");
		int id = -1;
		Book book = null;
		id = Integer.parseInt(idStr);
		if(id>0)
			book = bookService.getBook(id);
		if(book==null){
			response.sendRedirect(request.getContextPath() + "/error.jsp");
			return;
		}
		request.setAttribute("book", book);
		request.getRequestDispatcher("/WEB-INF/pages/book.jsp").forward(request, response);
	}
	
	protected void addToCart(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String idStr = request.getParameter("id");
		int id=-1;
		boolean flag = false;
		id=Integer.parseInt(idStr);
		if(id>0){
			ShoppingCart sc = BookStoreWebUtils.getShoppingCart(request);
			flag = bookService.addToCart(id, sc);
		}
		if(flag){
			getBooks(request, response);
			return;
		}
	}
	
	protected void remove(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String idStr = request.getParameter("id");
		int id =-1;
		id=Integer.parseInt(idStr);
		ShoppingCart sc = BookStoreWebUtils.getShoppingCart(request);
		bookService.removeItemFromShoppingCart(sc, id);
		if(sc.isEmpty()){
			request.getRequestDispatcher("/WEB-INF/pages/emptycart.jsp").forward(request, response);
			return;
		}
		request.getRequestDispatcher("/WEB-INF/pages/cart.jsp").forward(request, response);
	}
	
	protected void clear(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		ShoppingCart sc = BookStoreWebUtils.getShoppingCart(request);
		bookService.clearShoppingCart(sc);
		request.getRequestDispatcher("/WEB-INF/pages/emptycart.jsp").forward(request, response);
	}
	
	protected void cash(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		//1. 简单验证: 验证表单域的值是否符合基本的规范: 是否为空, 是否可以转为 int 类型, 是否是一个 email. 不需要进行查询
		//数据库或调用任何的业务方法.
		String username = request.getParameter("username");
		String accountId = request.getParameter("accountId");
		
		StringBuffer errors = validateFormField(username, accountId);
		
		//表单验证通过。 
		if(errors.toString().equals("")){
			errors = validateUser(username, accountId);
			
			//用户名和账号验证通过
			if(errors.toString().equals("")){
				errors = validateBookStoreNumber(request);
				
				//库存验证通过
				if(errors.toString().equals("")){
					errors = validateBalance(request, accountId);
				}
			}
		}
		
		if(!errors.toString().equals("")){
			request.setAttribute("errors", errors);
			request.getRequestDispatcher("/WEB-INF/pages/cash.jsp").forward(request, response);
			return;
		}
		
		//验证通过执行具体的逻辑操作
		bookService.cash(BookStoreWebUtils.getShoppingCart(request), username, accountId); 
		response.sendRedirect(request.getContextPath() + "/success.jsp");
	}

	private StringBuffer validateBalance(HttpServletRequest request, String accountId) {
		StringBuffer errors = new StringBuffer();
		ShoppingCart cart = BookStoreWebUtils.getShoppingCart(request);
		Account account = accountService.getAccount(Integer.parseInt(accountId));
		if(cart.getTotalMoney()>account.getBalance()){
			errors.append("余额不足");
		}
		return errors;
	}

	private StringBuffer validateBookStoreNumber(HttpServletRequest request) {
		StringBuffer errors = new StringBuffer();
		ShoppingCart cart = BookStoreWebUtils.getShoppingCart(request);
		for(ShoppingCartItem sci:cart.getItems()){
			int quantity = sci.getQuantity();
			int storeNumber = bookService.getBook(sci.getBook().getBook_id()).getStore_number();
			if(quantity>storeNumber){
				errors.append(sci.getBook().getTitle()+"库存不足<br>");
			}
		}
		return errors;
	}

	private StringBuffer validateUser(String username, String accountId) {
		boolean flag = false;
		User user = userService.getUserByUserName(username);
		StringBuffer error = new StringBuffer();
		if(user==null){
			error.append("用户不存在");
			return error;
		}else{
			int accountId2=user.getAccount_id();
			if(accountId.trim().equals(accountId2+"")){
				flag = true;
			}
		}
		if(!flag){
			error.append("用户名和账号不匹配");
		}
		return error;
	}

	private StringBuffer validateFormField(String username, String accountId) {
StringBuffer errors = new StringBuffer("");
		
		if(username == null || username.trim().equals("")){
			errors.append("用户名不能为空<br>");
		}
		
		if(accountId == null || accountId.trim().equals("")){
			errors.append("账号不能为空");			
		}
		
		return errors;
	}
	
}

JavawebProject/WebContent/WEB-INF/pages/book.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@ include file="/common.jsp" %>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>在此处插入标题</title>
</head>
<body>
	<center>
		<br><br>
		Title:${book.title}
		<br><br>
		Author:${book.author}
		<br><br>
		Price:${book.price }
		<br><br>
		PublishingDate:${book.publishing_date }
		<br><br>
		Remark:${book.remark }
		<br><br>
		<a href="bookServlet?method=getBooks&pageNo=${param.pageNo }&minPrice=${param.minPrice}&maxPrice=${param.maxPrice}">继续购物</a>
	</center>
</body>
</html>

JavawebProject/WebContent/WEB-INF/pages/books.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<%@page import="com.mchange.v1.db.sql.CBPCursor"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ include file="/common.jsp" %>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script type="text/javascript" src="/JavawebProject/WebContent/WEB-INF/pages/jquery-3.2.1.js"></script>
</head>
<body>
	<center>
	<c:if test="${param.title!=null }">
		您已经将${param.title}放入购物车中
		<br><br>
	</c:if>
	<c:if test="${!empty sessionScope.ShoppingCart}">
		您的购物车中有${sessionScope.ShoppingCart.bookNumber}本书,<a href="bookServlet?method=forwardPage&page=cart">查看购物车</a>
	</c:if>
		<br><br>
			<form action="bookServlet?method=getBooks" method="post">
			Price:<input type="text" size="1" name="minPrice"/> - 
				  <input type="text" size="1" name="maxPrice"/>
				  <input type="submit" value="Submit"/>
			</form>
			<br>
			<table cellpadding="10">
				<c:forEach items="${bookpage.list }" var="book">
					<tr>
						<td>
							<a href="bookServlet?method=getBook&pageNo=${bookpage.pageNo }&minPrice=${cb.minPrice}&maxPrice=${cb.maxPrice}&id=${book.book_id}">${book.title }</a>
							<br>
							${book.author }
						</td>
						<td>${book.price}</td>
						<td><a href="bookServlet?method=addToCart&pageNo=${bookpage.pageNo }&id=${book.book_id}&title=${book.title}">加入购物车</a></td>
					</tr>
				</c:forEach>
			</table>
			<br><br>
			共${bookpage.totalPageNumber }页
			&nbsp;&nbsp;
			当前第${bookpage.pageNo }页
			&nbsp;&nbsp;
			<c:if test="${bookpage.hasPrev }">
				<a href="bookServlet?method=getBooks&pageNo=1&minPrice=${cb.minPrice}&maxPrice=${cb.maxPrice}">首页</a>
				&nbsp;&nbsp;
				<a href="bookServlet?method=getBooks&pageNo=${bookpage.prevPage }&minPrice=${cb.minPrice}&maxPrice=${cb.maxPrice}">上一页</a>
			</c:if>
			&nbsp;&nbsp;
			<c:if test="${bookpage.hasNext }">
				<a href="bookServlet?method=getBooks&pageNo=${bookpage.totalPageNumber }&minPrice=${cb.minPrice}&maxPrice=${cb.maxPrice}">末页</a>
				&nbsp;&nbsp;
				<a href="bookServlet?method=getBooks&pageNo=${bookpage.nextPage }&minPrice=${cb.minPrice}&maxPrice=${cb.maxPrice}">下一页</a>
			</c:if>
			&nbsp;&nbsp;
			<a href="users.jsp">查看记录</a>
	</center>
</body>
</html>

JavawebProject/WebContent/WEB-INF/pages/cart.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ include file="/common.jsp"  %>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>在此处插入标题</title>
</head>
<body>
	<center>
		<br><br>
		<div id="bookNumber">您的购物车中共有${sessionScope.ShoppingCart.bookNumber}本书</div>
		<table cellpadding="10">
			<tr>
				<td>Title</td>
				<td>Quantity</td>
				<td>Price</td>
				<td>&nbsp;</td>
			</tr>
			<c:forEach items="${sessionScope.ShoppingCart.items }" var="item">
				<tr>
					<td>${item.book.title}</td>
					<td>${item.quantity }</td>
					<td>${item.book.price}</td>
					<td><a href="bookServlet?method=remove&id=${item.book.book_id}" class="delete" onclick="if(confirm('确定删除吗?')==false)return false;">删除</a></td>
				</tr>
			</c:forEach>
			<tr>
				<td colspan="4" id="totalMoney">总金额:￥${sessionScope.ShoppingCart.totalMoney }</td>
			</tr>
			<tr>
				<td colspan="4">
					<a href="bookServlet?method=getBooks">继续购物</a>
					&nbsp;&nbsp;&nbsp;
					<a href="bookServlet?method=clear">清空购物车</a>
					&nbsp;&nbsp;
					<a href="bookServlet?method=forwardPage&page=cash">结账</a>
				</td>
			</tr>
		</table>
	</center>
</body>
</html>

JavawebProject/WebContent/WEB-INF/pages/cash.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>在此处插入标题</title>
</head>
<body>
	<center>
		<br><br>
		您一共买了${sessionScope.ShoppingCart.bookNumber}本书
		<br>
		应付:￥${sessionScope.ShoppingCart.totalMoney}
		<br><br>
		<c:if test="${requestScope.errors != null }">
			<font color="red">${requestScope.errors}</font>
		</c:if>
		<form action="bookServlet?method=cash" method="post">
			<table cellpadding="10">
				<tr>
					<td>信用卡姓名</td>
					<td><input type="text" name="username"/></td>
				</tr>
				<tr>
					<td>信用卡账号</td>
					<td><input type="text" name="accountId"/></td>
				</tr>
				<tr>
					<td colspan="2"><input type="submit" value="结账"/></td>
				</tr>
			</table>
		</form>
	</center>
</body>
</html>

JavawebProject/WebContent/WEB-INF/pages/emptycart.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>在此处插入标题</title>
</head>
<body>
	<center>
	<h4>您的购物车为空</h4>
	<a href="bookServlet?method=getBooks">继续购物</a>
	</center>
</body>
</html>

JavawebProject/WebContent/WEB-INF/pages/trades.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>在此处插入标题</title>
</head>
<body>
		<center>
			<br><br>
			<h4>User:${user.user_name}</h4>
			<br><br>
			<table>
				<c:forEach items="${user.trades }" var="trade">
					<tr>
					<td>
					<table border="1" cellpadding="10" cellspacing="0">
						<tr>
							<td colspan="3">TradeTime:${trade.trade_time}</td>
						</tr>
						<c:forEach items="${trade.items }" var="item">
							<tr>
								<td>${item.book.title}</td>
								<td>${item.book.price}</td>
								<td>${item.quantity}</td>
							</tr>
						</c:forEach>
					</table>
					<br><br>
					</td>
					</tr>
				</c:forEach>
			</table>
		</center>
</body>
</html>